### ISSUE TITLE
Add support for different chunking strategies

### ISSUE THREAD

**Issue by dgarnitz** [dgarnitz/vectorflow#12]
Right now vectorflow only supports chunking by the an exact length passed in by the user, independent of how the content is structured. Ideally the user should be able to specify whether they want this strategy, or by paragraph, by sentence, etc.

**Comment by EteimZ** [comment]
Hi @dgarnitz I will love to work on this issue. I bet a chunking technique similar to langchain's [RecursiveCharacterTextSplitter](https://python.langchain.com/docs/modules/data_connection/document_transformers/text_splitters/recursive_text_splitter) could be of great use to vectorflow.

**Comment by dgarnitz** [comment]
@EteimZ I assigned it to you

**Comment by dgarnitz** [comment]
Fixed by @EteimZ  in https://github.com/dgarnitz/vectorflow/pull/30
