### ISSUE TITLE
Integration for MongoDB

### ISSUE THREAD

**Issue by prakul** [dgarnitz/vectorflow#34]
Hi, Can you please consider adding an integration for MongoDB Atlas Vector Search 

https://www.mongodb.com/products/platform/atlas-vector-search

**Comment by dgarnitz** [comment]
@prakul we will add that to our integration roadmap. Do you have a commercial need for the integration?

**Comment by farhan0167** [comment]
@dgarnitz I'll work on this

**Comment by dgarnitz** [comment]
Awesome, thanks!

**Comment by prakul** [comment]
Thanks @farhan0167! Please feel free to reach out regarding any product help with Atlas Vector Search.

**Comment by dgarnitz** [comment]
@farhan0167 completed this issue with his latest PR so I am closing it out. We will have a follow up PR with documentation in the README on how to utilize MongoDB. 

@prakul let me know if you have any questions or concerns. Thanks!
