### ISSUE TITLE
Add support for Chroma

### ISSUE THREAD

**Issue by dgarnitz** [dgarnitz/vectorflow#39]
vectorflow should integrate with and support Chroma as a target vector DB - https://docs.trychroma.com/

**Comment by farhan0167** [comment]
I would like to take this issue

**Comment by dgarnitz** [comment]
awesome!

**Comment by dgarnitz** [comment]
Please use the client-server model with the `HttpClient`. We do not currently plan to support local storage.

**Comment by dgarnitz** [comment]
After discussion with the team, determined this is not a good fit for now. No users are asking for it.
