### ISSUE TITLE
Suggestion: Docs website

### ISSUE THREAD

**Issue by antondubek** [dgarnitz/vectorflow#48]
For this project it would be good to see a documentation website with the various technical documentation and support outside of just the readme and main getvectorflow.com site.

Something simple using GitHub pages, mkdocs and hosted on docs.getvectorflow.com would be very user friendly with architectures, getting started examples and API docs.

Example:
https://kops.sigs.k8s.io/getting_started/install/
https://squidfunk.github.io/mkdocs-material/blog/2021/12/27/the-past-present-and-future/

**Comment by dgarnitz** [comment]
this has been resolved. See here for docs - https://vectorflow.dev-docs.dev/docs/
