### ISSUE TITLE
Add Batch Write into Milvus

### ISSUE THREAD

**Issue by dgarnitz** [dgarnitz/vectorflow#52]
Swap out the normal upload in Milvus (https://github.com/dgarnitz/vectorflow/blob/74b1f50e8784362323ea553360bc55a6bd2292b2/src/worker/vdb_upload_worker.py#L192-L216) for the batch update for faster upload. 

This sample code should provide guidance - https://github.com/milvus-io/pymilvus/blob/master/examples/example_bulkinsert_json.py

**Comment by david-vectorflow** [comment]
Not doing this, as we have removed milvus support

**Comment by tvvignesh** [comment]
@dgarnitz @david-vectorflow Hi. Updating the docs and website regarding removal of milvus support would be good. I tried setting the project up for last 3 hours without any success and finally noticed that there was no method to write embeddings to milvus

<img width="965" alt="image" src="https://github.com/dgarnitz/vectorflow/assets/1165845/1a19e152-2229-4477-bc23-c99f70f54c31">

Requesting to update the docs and website accordingly.

**Comment by dgarnitz** [comment]
@tvvignesh Super sorry to hear that you needed it! We were having dependency issues with Milvus and it was not being used in production by anyone so we removed it. Is there something I can do to help you get vectorflow spun up?

**Comment by tvvignesh** [comment]
Hi. Thanks for the reply. After seeing lack of support for milvus in vectorflow, I removed it and am sticking to handling all the ETL in python scripts itself as of now and it works. As of now, I am good, but if you plan to support Milvus in the future, would be happy to try it out.
