### ISSUE TITLE
Deploy Via Docker + HF = worker error

### ISSUE THREAD

**Issue by iguy0** [dgarnitz/vectorflow#61]
Hello,

I'm experiencing an issue with the docker deployment using a custom embedding model. I'm trying to use BAAI/bge-large-en-v1.5.

Below is my deployment and outputs.

### Configure vars
mkdir env_scripts
cd env_scripts
touch env_scripts/env_vars.env
nano env_scripts/env_vars.env

cat env_scripts/env_vars.env
```
INTERNAL_API_KEY=qxzZOs0LPqjgkJiv3279rqqxHgzi9k5r
POSTGRES_USERNAME=postgres
POSTGRES_PASSWORD=SuperSecret
POSTGRES_DB=vectorflow
POSTGRES_HOST=postgres
RABBITMQ_USERNAME=guest
RABBITMQ_PASSWORD=guest
RABBITMQ_HOST=rabbitmq
RABBITMQ_PORT=5672
EMBEDDING_QUEUE=embeddings
VDB_UPLOAD_QUEUE=vdb-upload
LOCAL_VECTOR_DB=qdrant
# Client Vars - Test
EMBEDDING_TYPE=HUGGING_FACE
VECTOR_DB_TYPE=QDRANT
TESTING_ENV=testing123
```

## Deploy via docker
docker pull rabbitmq
docker pull postgres
docker pull qdrant/qdrant
docker-compose build --no-cache
docker-compose up -d
# deploy HF model
cd src
docker build --file hugging_face/Dockerfile -t vectorflow_hf:latest .
docker run --network=vectorflow --name=vectorflow_hf -d --env-file=../env_scripts/env_vars.env vectorflow_hf:latest --model_name "BAAI/bge-large-en-v1.5"

# All containers appear normal at this point

## Testing
cat src/testing_client-custom.py
```
import os
import requests
import json
import dotenv
# Load environment variables from .env file
dotenv.load_dotenv(dotenv_path='../env_scripts/env_vars.env')

#####################
# Testing Variables #
#####################
filepath = './api/tests/fixtures/test_medium_text.txt'
url = "http://localhost:8000/embed"
internal_api_key = os.getenv("INTERNAL_API_KEY")
embedding_type = os.getenv("EMBEDDING_TYPE")
vector_db_type = os.getenv("VECTOR_DB_TYPE")
index_name = os.getenv("INDEX_NAME")
testing_environment = os.getenv("TESTING_ENV")

##################
# Testing script #
##################

headers = {
    "Authorization": internal_api_key,
}

data = {
    'EmbeddingsMetadata': json.dumps({
        "embeddings_type": embedding_type,
        "chunk_size": 384,
        "chunk_overlap": 128,
        "chunk_strategy": "PARAGRAPH",
        "hugging_face_model_name": "BAAI/bge-large-en-v1.5"
    }),
    'VectorDBMetadata': json.dumps({
        "vector_db_type": vector_db_type,
        "index_name": index_name,
        "environment": testing_environment
    })
}

files = {
    'SourceData': open(filepath, 'rb')
}

print("sending request")
response = requests.post(
    url,
    headers=headers,
    data=data,
    files=files
)

if response.status_code != 200:
    print(f"Error: {response.text}")
    print(f"Status code: {response.status_code}")
    exit(1)

response_json = response.json()
job_id = response_json['JobID']
print(f"Job ID: {job_id}")

# poll the server for the job status
url = f"http://localhost:8000/jobs/{job_id}/status"
job_status = None
while job_status != "COMPLETED" and job_status != "FAILED":
    headers = {
        "Authorization": internal_api_key,
    }

    response = requests.get(
        url,
        headers=headers
    )

    response_json = response.json()
    job_status = response_json['JobStatus']

print(f"Job status: {job_status}")
```

# Docker logs from "vectorflow_worker" container

```
wait-for-it.sh: waiting 15 seconds for rabbitmq:5672
wait-for-it.sh: rabbitmq:5672 is available after 7 seconds
--- Logging error ---
Traceback (most recent call last):
  File "/app/worker/worker.py", line 231, in callback
    os.environ["VECTOR_DB_KEY"] = vector_db_key
  File "/usr/local/lib/python3.9/os.py", line 684, in __setitem__
    value = self.encodevalue(value)
  File "/usr/local/lib/python3.9/os.py", line 756, in encode
    raise TypeError("str expected, not %s" % type(value).__name__)
TypeError: str expected, not NoneType
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/logging/__init__.py", line 1083, in emit
    msg = self.format(record)
  File "/usr/local/lib/python3.9/logging/__init__.py", line 927, in format
    return fmt.format(record)
  File "/usr/local/lib/python3.9/logging/__init__.py", line 663, in format
    record.message = record.getMessage()
  File "/usr/local/lib/python3.9/logging/__init__.py", line 367, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/app/worker/worker.py", line 283, in <module>
    start_connection()
  File "/app/worker/worker.py", line 276, in start_connection
    consume_channel.start_consuming()
  File "/usr/local/lib/python3.9/site-packages/pika/adapters/blocking_connection.py", line 1883, in start_consuming
    self._process_data_events(time_limit=None)
  File "/usr/local/lib/python3.9/site-packages/pika/adapters/blocking_connection.py", line 2044, in _process_data_events
    self.connection.process_data_events(time_limit=time_limit)
  File "/usr/local/lib/python3.9/site-packages/pika/adapters/blocking_connection.py", line 851, in process_data_events
    self._dispatch_channel_events()
  File "/usr/local/lib/python3.9/site-packages/pika/adapters/blocking_connection.py", line 567, in _dispatch_channel_events
    impl_channel._get_cookie()._dispatch_events()
  File "/usr/local/lib/python3.9/site-packages/pika/adapters/blocking_connection.py", line 1510, in _dispatch_events
    consumer_info.on_message_callback(self, evt.method,
  File "/app/worker/worker.py", line 238, in callback
    logging.error('Error processing batch:', e)
Message: 'Error processing batch:'
Arguments: (TypeError('str expected, not NoneType'),)

```

Could you please point me in the right direction for resolving this ? 

Much appreciated!

**Comment by dgarnitz** [comment]
Hey, it looks like the `vector_db_key` variable is not being set. This is a bug on our part that it should not need to be set if you are running the vector db locally. 

trying passing in something like this:
```
headers = {
    "Authorization": os.getenv("INTERNAL_API_KEY"),
    "X-VectorDB-Key": "test-key,
}
```
and see if it fixes it

**Comment by dgarnitz** [comment]
Based on that it looks like it inferenced successfully. BAAI/bge-large-en-v1.5 does require 1.34 GB of RAM so if you're machine does not have a lot it won't work but I don't think thats the issue here. 

I'll investigate and get back to you

**Comment by dgarnitz** [comment]
I'm investigating this now. One thing I notice that will become an issue for you after this error is resolved is in the `vdb_upload_worker`, your `TESTING_ENV` variable should be the same name as the vector DB environment or URL that you are using. In this case it should be `qdrant`. I will update this in the docs since its confusing

**Comment by dgarnitz** [comment]
I just tested your configuration locally and I did not get the `psycopg2.OperationalError`. I suspect something happened where your connection was terminated, maybe with the container being idle. I will add in some connection retry functionality to fix this. In the interim, try restarting your rabbitmq and postgres containers.

Another heads up BTW, your code will fail in the `vdb_upload_worker` if you have not created a new collection inside qdrant after spinning it up because you are using a model with a 1024 dimensional vectors but the default qdrant instance is not configured with a collection for those dimensions. I will add this to the configuration script. 

I was ultimately able to get the embedding and upload to succeed with your configuration.

**Comment by dgarnitz** [comment]
I just merged this [PR](https://github.com/dgarnitz/vectorflow/pull/62) which adds additional logic to prevent the DB connection from closing quickly and will automatically try to establish a connection before DB calls. It will also retry if there is a connection error, and it does so in an idempotent way. Please let me know if this fixes the issue

**Comment by dgarnitz** [comment]
@iguy0 are you still encountering this issue?
